Fix for .NET 3.5 and 4.0 builds broken by MethodInfo.cs(103,26) error CS1061: 'System.Reflection.ParameterInfo' does not contain a definition for 'HasDefault Value'